### ISSUE TITLE
Library simplified

### ISSUE THREAD

**Issue by lfarah** [kayoslab/swift-pdf#3]
Hey @kayoslab, I'd like you to take a look [at my fork](https://github.com/lfarah/SwiftPDFGenerator/blob/master/README.md). I simplified the library folders and files to make it really easy for the devs to install and use the library as easy and quickly as possible.

What do you think?

**Comment by kayoslab** [comment]
I downloaded your fork, but there are some linker errors of your storyboard. I like your location of the `SwiftPDFGenerator` File and adapted this in the Project, therefore I won't merge them. Please check my changes in 7d7e19e
